export declare type ToggleSwitchTheme = Partial<{
    rootWidth: string;
    rootHeight: string;
    transitionSpeed: string;
    borderRadius: string;
    labelMovementRange: string;
    outerLabelWidth: string;
    outerLabelHeight: string;
    innerLabelWidth: string;
    innerLabelHeight: string;
    innerLabelBackgroundColor: string;
    backgroundColor: string;
    backgroundColorChecked: string;
    backgroundColorDisabled: string;
    backgroundColorHover: string;
    backgroundColorFocus: string;
    focusOutline: string;
    color: string;
    colorChecked: string;
    colorDisabled: string;
    colorCheckedDisabled: string;
    colorHover: string;
    colorFocus: string;
    toggleIconWidth: string;
    toggleIconHeight: string;
    toggleIconDisplay: string;
    outerLabelBorder: string;
    outerLabelBorderChecked: string;
    outerLabelBorderDisabled: string;
    outerLabelBorderHover: string;
    outerLabelBorderHoverChecked: string;
    innerLabelBorder: string;
    innerLabelBorderChecked: string;
    innerLabelBorderDisabled: string;
    innerLabelBorderHover: string;
    innerLabelBorderHoverChecked: string;
}>;
export declare const core: ToggleSwitchTheme;
